:construction_worker: Added docker job to the CI

diff --git a/.github/workflows/area.yml b/.github/workflows/area.yml
--- a/.github/workflows/area.yml
+++ b/.github/workflows/area.yml
@@ -102,6 +102,27 @@ jobs:
         run: flutter build apk
         working-directory: mobile
 
+# Docker
+  docker:
+    runs-on: ubuntu-latest
+    needs:
+      - frontend
+      - backend
+      - mobile
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Build docker container
+        run: |
+          docker compose build || { echo "Docker build failed"; exit 1; }
+        working-directory: .
+
+      - name: Check build success
+        if: failure()
+        run: |
+          echo "Docker compose build encountered an error. Workflow cancelled."
+          exit 1
+
 # Deploy documentation
   deploy-documentation:
     runs-on: ubuntu-latest
